name: linux
on: [push]

permissions:
  contents: write

jobs:
  action-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The ${{ github.workspace }} is now ready to test your code on the runner."
      - run: ls ${{ github.workspace }}
      - run: sudo apt update
      - run: sudo apt install git gcc nasm

      - run: echo "install objconv"
        shell: bash
      - run: |
          git clone https://github.com/gitGNU/objconv.git
          cp objconv/bin/objconv_ubuntu_* objconv/bin/objconv
          chmod +x objconv/bin/objconv
          export PATH=$PATH:`pwd`/objconv/bin
          echo $PATH
          whereis objconv
          objconv -h

      - run: echo "start build..."
      - run: make
      - run: echo "end build..."

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - run: echo "start packing..."
      - name: Export package
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "ASSET=build/disk.img" >> $GITHUB_ENV
      - run: echo "end packing..."

      - name: Upload the package
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.ASSET }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
